/// It returns holidays from 1955 to the current year
/// This file is automatically generated by the `generator`
/// Or it can be created manually. See README.md for details or help
pub mod dates;
/// generates holiday data from a CSV file which downloaded from Cabinet Office Website
pub mod generator;

/// processing to determine national holidays
pub mod holiday;
