name: Regular update process for holiday data

on:
  schedule:
    - cron: '1 2 * * 1'
  workflow_dispatch:

jobs:
  build:
    name: update holiday data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: download
        run: |
          cargo run -- update
          cargo fmt
      - name: commit & push changes
        env:
          CI_COMMIT_AUTHOR: github-actions
          CI_COMMIT_MESSAGE: update holiday cache data from github action
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: ${{ env.CI_COMMIT_AUTHOR }}
          message: ${{ env.CI_COMMIT_MESSAGE }}

